### ISSUE TITLE
Getting 400 when trying to send emails

### ISSUE THREAD

**Issue by genericlady** [andrewtimberlake/bamboo_sparkpost#4]
@andrewtimberlake updated the original issue.

I can't figure out the problem. If I use sparkposts elixir library it sends fine but when I use bamboo I get 400. What could the problem be?

Currently am using bamboo v0.5.1

```
** (Bamboo.SparkPostAdapter.ApiError) There was a problem sending the email through the SparkPost API.

Here is the response:

%HTTPoison.Response{body: "{ \"errors\": [ { \"message\": \"Invalid domain\", \"description\": \"Unconfigured Sending Domain <learanthon.nyc> \", \"code\": \"7001\" } ] }", headers: [{"Date", "Tue, 11 Apr 2017 17:55:14 GMT"}, {"Content-Type", "application/json"}, {"Content-Length", "129"}, {"Connection", "keep-alive"}, {"Vary", "Accept"}, {"Server", "msys-http"}, {"Cache-Control", "no-cache, no-store"}], status_code: 400}


Here are the params we sent:

%{"content" => %{"from" => %{"email" => "submissions@learanthon.nyc", "name" => nil}, "headers" => %{}, "html" => "<div class=\"jumbotron\">\n  <h2>Welcome to learnathon.nyc!</h2>\n</div>\n", "reply_to" => "submissions@learnathon.nyc", "subject" => "Welcome to learnathon.nyc!", "text" => "welcome to the learnathon.nyc!\n"}, "key" => "[FILTERED]", "recipients" => [%{"address" => %{"email" => "yianna@learnathon.nyc", "name" => nil}}]}

    (bamboo_sparkpost) lib/bamboo/adapters/sparkpost_adapter.ex:53: Bamboo.SparkPostAdapter.deliver/2
              (bamboo) lib/bamboo/mailer.ex:123: Bamboo.Mailer.deliver_now/3
```

**Comment by andrewtimberlake** [comment]
Please try with the master branch and let me know if that fixes it.

**Comment by genericlady** [comment]
I'll try the master branch today but I solved the 301. It was an url problem. I'm still having problems sending with it.

I'll post my error as soon as I can. Thanks for the help.

**Comment by genericlady** [comment]
@andrewtimberlake I updated the error, why would someone get invalid domain? I verified my sending domain using email.

Plus it sends fine with sparkpost library

**Comment by lessless** [comment]
@genericlady you can use Wireshark/tap in with `IO.inspect` to inspect packets and see what's the difference in the requests between bamboo_sparkpost and official library

**Comment by andrewtimberlake** [comment]
Cleaning out old issues. If this is still an issue, please reopen with additional information.
